package:
  name: dxchange
  version: '0.0.2'

source:
  git_url: https://github.com/data-exchange/data-exchange.git
  
build:
  number: 0

requirements:
  build:
    - python
    - setuptools
 
  run:
    - python
    - numpy    - h5py    - six    - netcdf4    - spefile    - edffile    - tifffile    - dxfile
test:
  # Python imports
  imports:
    - dxchange
    - dxchange.reader
    - dxchange.writer
    - dxchange.exchange

about:
  home: http://dxchange.readthedocs.org
  license: BSD-3
  summary: 'Tomographic data file readers.'
