package:
  name: dxchange
  version: '0.0.1'

source:
  git_url: https://github.com/data-exchange/data-exchange.git
  
build:
  number: 0

requirements:
  build:
    - python
    - setuptools
 
  run:
    - python
    - h5py

test:
  # Python imports
  imports:
    - dxchange

about:
  home: http://dxchange.readthedocs.org
  license: BSD-3
  summary: 'Tomographic data file readers.'
